const $=id=>document.getElementById(id),current=chrome.runtime.getManifest().version;$("version").textContent="v"+current;const btn=$("update"),status=$("status");function setStatus(t,c=""){status.textContent=t;status.className="status "+c}function newer(a,b){const x=String(a).replace(/^v/i,"").split(".").map(Number),y=String(b).replace(/^v/i,"").split(".").map(Number);for(let i=0;i<4;i++){if((x[i]||0)!==(y[i]||0))return(x[i]||0)>(y[i]||0)}return false}async function check(){btn.disabled=true;btn.textContent="Checking…";setStatus("Checking the latest verified release…");try{const r=await chrome.runtime.sendMessage({type:"vf-check-update"});if(!r?.ok)throw new Error(r?.error||"Update check failed");if(r.update&&newer(r.info.version,current)){setStatus("Version "+r.info.version+" is available.","new");btn.disabled=false;btn.textContent="Update now";btn.onclick=update}else{setStatus("Everything is up to date.","ok");btn.disabled=false;btn.textContent="Check again";btn.onclick=check}}catch(e){setStatus(e.message||"Could not check for updates.","err");btn.disabled=false;btn.textContent="Try again";btn.onclick=check}}async function update(){btn.disabled=true;btn.textContent="Updating…";setStatus("Installing and verifying the update…");const r=await chrome.runtime.sendMessage({type:"vf-update-now"});if(!r?.ok){setStatus(r?.error||"Update could not be started.","err");btn.disabled=false;btn.textContent="Try again";btn.onclick=check;return}setStatus("Update started… verifying files and native bridge.","ok");
  let checks=0;
  const timer=setInterval(async()=>{
    checks++;
    try{
      const s=await chrome.runtime.sendMessage({type:"vf-update-status"});
      const st=s?.result?.status;
      if(st?.message) setStatus(st.message,"ok");
      if(st?.ok===false || checks>=120){clearInterval(timer);}
    }catch{}
  },500);
}btn.onclick=check;check();
const sites=[["XVideos","xvideos.com"],["Pornhub","pornhub.com"],["xHamster","xhamster.com"],["XNXX","xnxx.com"],["YouPorn","youporn.com"],["Eporner","eporner.com"],["RedTube","redtube.net"],["Sxyprn","sxyprn.com"],["SpankBang","spankbang.com"]];const sitesEl=$("sites");for(const[name,domain]of sites){const a=document.createElement("a");a.className="site";a.href="https://"+domain+"/";a.target="_blank";a.rel="noopener noreferrer";const img=document.createElement("img");img.alt="";img.src="https://icons.duckduckgo.com/ip3/"+domain+".ico";const fb=document.createElement("div");fb.className="site-fallback";fb.textContent=name[0];fb.style.display="none";img.onerror=()=>{img.style.display="none";fb.style.display="grid"};const span=document.createElement("span");span.textContent=name;a.append(img,fb,span);sitesEl.appendChild(a)}(async()=>{try{const r=await chrome.runtime.sendMessage({type:"vf-health"}),el=$("health");if(r?.health?.ok){el.textContent="● System healthy";el.className="health ok"}else if(r?.health){el.textContent="● Diagnostics available";el.className="health bad"}else el.textContent="● Health check pending"}catch{$("health").textContent="● Health unavailable"}})();